### PR TITLE
Dev mode

### PR DESCRIPTION
**Pull request by Devoxin**

### CODE REVIEW

**Comment by Aetheryx** [comment]
ik vind helemaal mooi

**Comment by ParadoxOrigins** [comment]
dont spam my mailbox with random characters kthx

**Comment by Aetheryx** [comment]
no u

**Comment by Aetheryx** [comment]
here I'll try doing it in french:
c'est la beaucoup jolie

**Comment by ParadoxOrigins** [comment]
that sentence doesn't make any sense

**Comment by Aetheryx** [comment]
u don't make any sense

**Comment by ParadoxOrigins** [comment]
no u

**Comment by Aetheryx** [comment]
no u tbh

**Comment by Aetheryx** [comment]
stinky

**Comment by ParadoxOrigins** [comment]
webhook ratelimit when

**Comment by Aetheryx** [comment]
dunno

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by Aetheryx** [comment]
f

**Comment by ParadoxOrigins** [comment]
f

**Comment by Aetheryx** [comment]
ok nvm no can do

**Comment by Devoxin** [comment]
STAHP ALL I HEAR IS BEEPS FROM YOUR COMMIT CHANNEL

**Comment by Aetheryx** [comment]
no u @Devoxin

**Comment by ParadoxOrigins** [comment]
no u

**Comment by Devoxin** [comment]
heck off

**Comment by Aetheryx** [comment]
hey I wonder if I can.. <@180093157554388993> is a bitch

**Comment by Devoxin** [comment]
cunt :(

**Comment by Aetheryx** [comment]
LUL https://why-are-you-buying-clothes-at.the-soup.store/419d48.png

**Comment by ParadoxOrigins** [comment]
oh that worked

**Comment by Aetheryx** [comment]
@everyone @here

**Comment by ParadoxOrigins** [comment]
webhooks op tbh

**Comment by Aetheryx** [comment]
same tbh

**Comment by ParadoxOrigins** [comment]
I GOT 15 EMAILS FROM THIS SHIT (╯°□°）╯︵ ┻━┻

**Comment by Aetheryx** [comment]
shh bby is ok

**Pull request merged**
