### PR TITLE
Added some error checks, changed how users are fetched, used es6 synt…

### PR DESCRIPTION
**Pull request by Samoxive**
…ax for iterating over collections

### CODE REVIEW

**Comment by Aetheryx** [comment]
Regarding [this](https://github.com/Aetheryx/remindme/pull/14/files#diff-ee78c500fd636080ce85758897b0559bR20):
Wouldn't the values be flipped in your PR? 
forEach uses [value, key](https://i.imgur.com/kIwQz6o.png), which is what was being used prior to this PR, and for..of uses [key, value](https://i.imgur.com/uWERGa2.png). Your PR does not seem to comply with the flipped order, as far as I can tell?

**Comment by Samoxive** [comment]
Right, pushing a fix.

**Comment by Samoxive** [comment]
[Here](https://github.com/Aetheryx/remindme/blob/master/src/remindmebot.js#L51) `config.botlists.x` is used to get tokens but in the current state of config validation and the example, tokens are in the `config.keys` object, we should fix the discrepancy.

**Comment by Aetheryx** [comment]
The example config is outdated. I'll be pushing a fix to update it to use `config.keys`, where the token is stored aswell.

**Pull request merged**
